# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/cis371/cis371/lab2/lab2.cache/wt [current_project]
set_property parent.project_path /home/cis371/cis371/lab2/lab2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/cis371/cis371/lab2/lc4_divider.v
  /home/cis371/cis371/lab2/lc4_alu.v
}
read_xdc /home/cis371/cis371/lab2/constraints/lc4_system.xdc
set_property used_in_implementation false [get_files /home/cis371/cis371/lab2/constraints/lc4_system.xdc]

synth_design -top lc4_alu -part xc7z020clg484-1
write_checkpoint -noxdef lc4_alu.dcp
catch { report_utilization -file lc4_alu_utilization_synth.rpt -pb lc4_alu_utilization_synth.pb }
